# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "lastfm_tools"
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["paulmillr"]
  s.date = "2012-03-11"
  s.description = "A backuper, helper and data analyzer for Last.fm API 2.0"
  s.email = "paul@paulmillr.com"
  s.executables = ["lastfmtools"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".rspec",
    "CHANGELOG.md",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/lastfmtools",
    "lastfm_tools.gemspec",
    "lib/lastfm_tools.rb",
    "lib/lastfm_tools/analyzer.rb",
    "lib/lastfm_tools/backuper.rb",
    "lib/lastfm_tools/query_parser.rb",
    "spec/analyzer_spec.rb",
    "spec/backuper_spec.rb",
    "spec/fixtures/changed_tags.json",
    "spec/fixtures/new_tags.json",
    "spec/fixtures/new_tracks.json",
    "spec/fixtures/recent_tracks.json",
    "spec/fixtures/tags.json",
    "spec/fixtures/tracks.json",
    "spec/query_parser_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/paulmillr/lastfm_tools"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Last.FM backuper, helper and data analyzer."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<lastfm>, ["= 1.4.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
    else
      s.add_dependency(%q<lastfm>, ["= 1.4.0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<rdoc>, [">= 0"])
    end
  else
    s.add_dependency(%q<lastfm>, ["= 1.4.0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<rdoc>, [">= 0"])
  end
end

